### ISSUE TITLE
Cucumber

### ISSUE THREAD

**Issue by PrzemyslawFormella** [JoannaMilewska/cypressTests#4]
https://cucumber.io/docs/installation/javascript/

To install Cucumber in a JavaScript environment, you will need to have Node.js and npm (Node Package Manager) installed on your computer.

Here are the steps to install Cucumber in a JavaScript project:

![image](https://user-images.githubusercontent.com/26028284/217751520-a57a7ae5-4fbc-49ef-bdef-d7fe6ad7021e.png)

![image](https://user-images.githubusercontent.com/26028284/217751630-45fa5b53-f122-4667-9627-32d44845529d.png)

![image](https://user-images.githubusercontent.com/26028284/217751980-45aa86fb-2571-4c87-a577-b39afa4022a3.png)

![image](https://user-images.githubusercontent.com/26028284/217751779-11a2c934-8436-4a19-a6f8-d6c3f9e59078.png)

You should see the output of your Cucumber tests in the console.

**Comment by JoannaMilewska** [comment]
done
