### ISSUE TITLE
Correct Login to Home Page

### ISSUE THREAD

**Issue by PrzemyslawFormella** [JoannaMilewska/cypressTests#5]
Here is an example test case for correctly logging in to the home page for https://magento.softwaretestingboard.com/:

**Title:** Correct Login to Home Page Test

**Objective**: Verify that a user can successfully log in to the home page of https://magento.softwaretestingboard.com/.

**Steps**:

1.     Open a web browser and navigate to the home page of https://magento.softwaretestingboard.com/
2.     Locate the login section on the home page and enter a valid username and password.
3.     Click the "Submit" or "Login" button.
4.     Verify that the user is redirected to the correct page, such as a dashboard or a personalized home page.
5.     Verify that the user's name or username is displayed on the page, indicating that they have successfully logged in.
6.     Log out of the account and repeat the test steps with an invalid username and password to verify that the system handles incorrect login attempts appropriately.

**Expected Result:** The user should be able to successfully log in to the home page and access their account information. The system should handle incorrect login attempts appropriately.

**Notes**: This test can be repeated on various browsers and devices to ensure compatibility with different environments.

**BDD:** 
**Scenario**: Correct Login to Home Page
**Given** the user is on the login page of https://magento.softwaretestingboard.com/
**When** the user enters a valid username and password
**And** clicks the "Login" button
**Then** the user should be redirected to the home page
**And** the page should display a message confirming that the user has logged in successfully
**And** the user should be able to access all the features available to logged-in users

**Comment by JoannaMilewska** [comment]
.
